# This file was generated by GoReleaser. DO NOT EDIT.
class Formatforest < Formula
  desc "Simple and elegant blogging engine written in Go."
  homepage "https://formatforest.com"
  version "0.0.4"
  bottle :unneeded

  if OS.mac?
    url "https://gitlab.com/nadimk/formatforest/uploads//formatforest_0.0.4_macos_amd64.zip"
    sha256 "4fd3018f9c38c584825579afa7d8fc3c219fd4640f8a44d22d02a5a2869075aa"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://gitlab.com/nadimk/formatforest/uploads//formatforest_0.0.4_linux_amd64.zip"
      sha256 "9f50b888f7d85bfd9d88d031c08c0dfb1dafc294917f072f3f7fa72cb318740e"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://gitlab.com/nadimk/formatforest/uploads//formatforest_0.0.4_linux_arm64.zip"
        sha256 "2fe7022d68ec5312c1caec528358dbe18c915dcc1f0e7c2e08fa395485c72d97"
      else
        url "https://gitlab.com/nadimk/formatforest/uploads//formatforest_0.0.4_linux_armv6.zip"
        sha256 "6ba12c307250cc2b681c0adb815de9b42f3c498610099190bf360acf3209e673"
      end
    end
  end

  def install
    bin.install "formatforest"
  end
end
