project_name: formatforest

builds:
  - main: ./cmd/formatforest/main.go
    gcflags:
      - -e
    goos:
      - windows
      - linux
      - darwin
      - freebsd
    goarch:
      - amd64
      - 386
      - arm64
      - arm

archives:
  - replacements:
      darwin: macos
    format: zip
    files:
      - LICENSE
      - examples/*
      - README.md

changelog:
  skip: false
  sort: asc

release:
  gitlab:
    owner: nadimk
    name: formatforest

brews:
  - gitlab:
      owner: nadimk
      name: formatforest
    commit_author:
      name: Nadim Kobeissi
      email: nadim@nadim.computer
    folder: HomebrewFormula
    homepage: "https://formatforest.com"
    description: "Simple and elegant blogging engine written in Go."

scoop:
  bucket:
    owner: nadimk
    name: formatforest
  commit_author:
    name: Nadim Kobeissi
    email: nadim@nadim.computer
  homepage: "https://formatforest.com"
  description: "Simple and elegant blogging engine written in Go."
  license: "https://www.gnu.org/licenses/gpl-3.0.en.html"
