project_name: formatforest

builds:
  - main: ./cmd/formatforest/main.go
    gcflags:
      - -e
    goos:
      - windows
      - linux
      - darwin
      - freebsd
    goarch:
      - amd64
      - 386
      - arm64
      - arm

archives:
  - format: zip
    files:
      - LICENSE
      - examples/*
      - README.md

changelog:
  skip: false
  sort: asc

release:
  github:
    owner: nadimkobeissi
    name: formatforest

brews:
  - repository:
      owner: nadimkobeissi
      name: formatforest
    commit_author:
      name: Nadim Kobeissi
      email: nadim.kobeissi@outlook.com
    folder: HomebrewFormula
    homepage: "https://formatforest.com"
    description: "Simple and elegant blogging engine written in Go."

scoops:
  repository:
    owner: nadimkobeissi
    name: formatforest
  commit_author:
    name: Nadim Kobeissi
    email: nadim.kobeissi@outlook.com
  homepage: "https://formatforest.com"
  description: "Simple and elegant blogging engine written in Go."
  license: "https://www.gnu.org/licenses/gpl-3.0.en.html"
